farms/urls.py
from django.urls import path
from .views import PostListView, PostCreateView, PostDetailView, PostUpdateView, PostDeleteView
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='home'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/', PostCreateView.as_view(), name = 'post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

ricefarm/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('farms.urls'))
]

farms/models.py
from django.db import models
from django.urls import reverse

class Farm(models.Model):
    row = models.IntegerField()
    col = models.IntegerField()
    lat = models.DecimalField(max_digits=30, decimal_places=15)
    lng = models.DecimalField(max_digits=30, decimal_places=15)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

farms/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Farm
# Create your views here.

farms = [
    {
        'row' : 12,
        'col' : 10,
        'lat' : 35.23123,
        'lng' : 35.2341
    },
    {
        'row' : 23,
        'col' : 14,
        'lat' : 50.23123,
        'lng' : 38.2341
    },

]



class PostListView(ListView):
    model = Farm
    template_name = 'farms/index.html'
    context_object_name = 'farms'

class PostDetailView(DetailView):
    model = Farm

class PostDetailView(DetailView):
    model = Farm

class PostCreateView(CreateView):
    model = Farm
    fields = ['row', 'col', 'lat', 'lng']
    success_url = '/post'

    def form_valid(self, form):
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        ctx = super(PostCreateView, self).get_context_data(**kwargs)
        ctx['farms'] = Farm.objects.all()
        return ctx


class PostUpdateView(UpdateView):
    model = Farm
    fields = ['row', 'col', 'lat', 'lng']

    def form_valid(self, form):
        return super().form_valid(form)



class PostDeleteView(DeleteView):
    model = Farm
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

farms/templates/farms/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>농사맨</title>
  </head>
  <body>
    {% block content %}
    {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

farms/templates/farms/farm_confirm_delete.html
{% extends "farms/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>등록된 논을 삭제하시겠습니까? "{{ object.lat }},{{ object.lng }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">삭제</button>
                <a class="btn btn-outline-secondary" href="{% url 'home'%}">취소</a>
            </div>
        </form>
    </div>
{% endblock content %}

farms/templates/farms/farm_detail.html
{% extends "farms/base.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.lat }},{{ object.lng}}</a>
        <small class="text-muted">{{ object.row}},{{object.col}}</small>
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
          </div>
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

farms/templates/farms/farm_form.html
{% extends "farms/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div id="map" style="width:100%;height:50vh"></div>
<p><em>지도를 클릭해주세요!</em></p> 
<div id="clickLatlng"></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=0c1c1ecf62b9129e1a3e52d50c6affd9"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new kakao.maps.LatLng(36.9398769229341, 126.92220064373734), // 지도의 중심좌표
        level: 2, // 지도의 확대 레벨
        mapTypeId: kakao.maps.MapTypeId. SKYVIEW
    };

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

// 지도를 클릭한 위치에 표출할 마커입니다
var marker = new kakao.maps.Marker({ 
    // 지도 중심좌표에 마커를 생성합니다 
    position: map.getCenter() 
}); 
marker.setMap(map);

kakao.maps.event.addListener(map, 'click', function(mouseEvent) {        
    
    // 클릭한 위도, 경도 정보를 가져옵니다 
    var latlng = mouseEvent.latLng; 
    
    // 마커 위치를 클릭한 위치로 옮깁니다
    marker.setPosition(latlng);

    var form = document.getElementById("my-form")
    form.lat.value = latlng.getLat()
    form.lng.value = latlng.getLng()
    
});


var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png"; 
var imageSize = new kakao.maps.Size(24, 35); 
var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize); 

function setMarker(id, row, col, lat, lng){
    var FarmMarker = new kakao.maps.Marker({
        map: map, // 마커를 표시할 지도
        position: new kakao.maps.LatLng(lat, lng), // 마커를 표시할 위치
        title : col + ',' + row + "갯수 : " + col*row, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
        image : markerImage // 마커 이미지 
    });
}



</script>

{% for farm in farms %}
    <script>
        setMarker('{{farm.id}}','{{farm.row}}','{{farm.col}}','{{farm.lat}}','{{farm.lng}}');
    </script>
{% endfor %}

</script>

    <div class="content-section">
            <form id="my-form" method="POST">
            {% csrf_token %}

                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">논 추가</legend>
                    
    
    <div id="div_id_row" class="control-group"> <label for="id_row" class="control-label requiredField">
                    가로 갯수<span class="asteriskField">*</span> </label> <div class="controls"> <input type="number" name="row" class="numberinput" required="" id="id_row"> </div> </div> <div id="div_id_col" class="control-group"> <label for="id_col" class="control-label requiredField">
                    세로 갯수<span class="asteriskField">*</span> </label> <div class="controls"> <input type="number" name="col" class="numberinput" required="" id="id_col"> </div> </div> <div id="div_id_lat" class="control-group"> <label for="id_lat" class="control-label requiredField">
                    위도<span class="asteriskField">*</span> </label> <div class="controls"> <input type="number" name="lat" step="1e-15" class="numberinput" required="" id="id_lat"> </div> </div> <div id="div_id_lng" class="control-group"> <label for="id_lng" class="control-label requiredField">
                    경도<span class="asteriskField">*</span> </label> <div class="controls"> <input type="number" name="lng" step="1e-15" class="numberinput" required="" id="id_lng"> </div> </div>
    
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">등록</button>
                </div>
            </form>
    </div>
    <div id = "home">
        <button class="btn btn-outline-info">
            <a href = "/">논 목록으로 돌아가기</a>
        </button>
    </div>
    
{% endblock content %}

farms/templates/farms/index.html
{% extends 'farms/base.html' %}
{% block content %}
<div id="map" style="width:100%;height:600px;"></div>
<div id="clickLatlng"></div>

<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=0c1c1ecf62b9129e1a3e52d50c6affd9"></script>
<script>
var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
    mapOption = { 
        center: new kakao.maps.LatLng(36.9398769229341, 126.92220064373734), // 지도의 중심좌표
        level: 2, // 지도의 확대 레벨
        mapTypeId: kakao.maps.MapTypeId. SKYVIEW
    };

var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다

var imageSrc = "https://t1.daumcdn.net/localimg/localimages/07/mapapidoc/markerStar.png"; 
var imageSize = new kakao.maps.Size(24, 35); 
var markerImage = new kakao.maps.MarkerImage(imageSrc, imageSize); 

function setMarker(id, row, col, lat, lng){
    var FarmMarker = new kakao.maps.Marker({
        map: map, // 마커를 표시할 지도
        position: new kakao.maps.LatLng(lat, lng), // 마커를 표시할 위치
        title : col + ',' + row + "갯수 : " + col*row, // 마커의 타이틀, 마커에 마우스를 올리면 타이틀이 표시됩니다
        image : markerImage
    });
    var link = '<a href="kakaomap://look?p=' + lat + ',' + lng + '" style="color:blue">길찾기</a>'
    var infowindow = new kakao.maps.InfoWindow({
        content: "가로 : " + row + ','+"세로 : " + col +  "<br>갯수 : " + col*row + '<br>' + link + '<br><a href="post/'+ id +'/delete/" style="color:blue">삭제</a>    ',
        removable : true,
    });
    
    kakao.maps.event.addListener(FarmMarker, 'click', makeOverListener(map, FarmMarker, infowindow));
}

function makeOverListener(map, marker, infowindow) {
    return function() {
        infowindow.open(map, marker);
    };
}
function locationLoadSuccess(pos){
    // 현재 위치 받아오기
    var currentPos = new kakao.maps.LatLng(pos.coords.latitude,pos.coords.longitude);

    // 지도 이동(기존 위치와 가깝다면 부드럽게 이동)
    map.panTo(currentPos);

    // 마커 생성
    var marker = new kakao.maps.Marker({
        position: currentPos
    });

    // 기존에 마커가 있다면 제거
    marker.setMap(map);
};

function locationLoadError(pos){
    alert('위치 정보를 가져오는데 실패했습니다.');
};

// 위치 가져오기 버튼 클릭시
function getCurrentPosBtn(){
    navigator.geolocation.getCurrentPosition(locationLoadSuccess,locationLoadError);
};


</script>
<button type="button" class="btn btn-lg btn-primary" id="getMyPositionBtn" onclick="getCurrentPosBtn()">내 위치 가져오기</button>
{% for farm in farms %}
    <script>
        setMarker('{{farm.id}}','{{farm.row}}','{{farm.col}}','{{farm.lat}}','{{farm.lng}}');
    </script>
{% endfor %}
<br>
<div id = "admin">
    <button>
        <a href = "post/">논 추가</a>
    </button>
</div>
{% endblock content %}